on: push
jobs:
  build-lib:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - run: npm install
    - run: npm run build
    - uses: actions/upload-artifact@v2
      with:
        name: lib
        path: dist/
  build-demo:
    needs: build-lib
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - run: npm install
    - uses: actions/download-artifact@v2
      with:
        name: lib
        path: ./dist
    - run: npm run build
    - uses: actions/upload-artifact@v2
      with:
        name: demo
        path: demo/dist/
